"""Plot pulse-rate histograms generated by eel_data_preprocessing.py.

This script loads multi-timescale pulse rate histograms and generates visualizations
in two styles:
1. Global pulse rate plots: Single line plot showing overall activity across all sessions
2. Session-wise scatter plots: Individual session points plus aggregate statistics

Each timescale (minute, hour, day, month, year) is plotted separately with custom
x-axis formatting for readability (e.g., clock times for hourly data, month names, etc.).

The scatter plots show:
- Blue points: Individual session pulse rates (alpha-transparent to show density)
- Red line: Median pulse rate across active sessions (sessions with any recorded pulses)
- Red shading: Either percentile range (16-84th) or bootstrap confidence interval,
  depending on USE_BOOTSTRAP configuration

Variation estimation methods:
- Percentile (default): Shows the spread of individual session values directly
- Bootstrap: Estimates confidence interval around the median itself via resampling.
  More robust with sparse data; explicitly quantifies median estimate uncertainty.

Note: Session-wise summaries exclude zero-rate sessions to avoid sparse pulse types
from collapsing to a flat zero Hz median.
"""

# %%
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from dateutil.relativedelta import relativedelta
from tqdm import tqdm

from data_paths import activity_hist_dir, processed_figures_dir

#################################
############# CONFIG #############
#################################

# Variation estimation method for session-wise plots
USE_BOOTSTRAP = (
    True  # If True, use bootstrap CI around median. If False, use percentiles.
)
BOOTSTRAP_ITERATIONS = 1000  # Number of resampling iterations for bootstrap
BOOTSTRAP_CI_LEVEL = (
    95  # Confidence level for bootstrap CI (e.g., 95 = 2.5th-97.5th percentiles)
)

PULSE_TYPES = {
    "all": {
        "label": "all pulses",
        "suffix": "_all",
        "figures_subdir": "all_pulses",
        "hist_subdir": "all_pulses_hist",
    },
    "double": {
        "label": "double pulses",
        "suffix": "_dp",
        "figures_subdir": "double_pulses",
        "hist_subdir": "double_pulses_hist",
    },
    "wide": {
        "label": "wide pulses",
        "suffix": "_wide",
        "figures_subdir": "wide_pulses",
        "hist_subdir": "wide_pulses_hist",
    },
    "fat": {
        "label": "fat pulses",
        "suffix": "_fat",
        "figures_subdir": "fat_pulses",
        "hist_subdir": "fat_pulses_hist",
    },
}
"""
Configuration for different pulse type analyses. Each specifies:
- label: Human-readable name for plot titles
- suffix: File suffix to differentiate output files
- figures_subdir: Output subdirectory for this pulse type's plots
- hist_subdir: Input subdirectory containing preprocessed histograms
"""


def select_pulse_type(default="all"):
    """
    Prompt user to select which pulse type plots to generate.

    Args:
        default (str): Default pulse type if user provides no input

    Returns:
        str: Selected pulse type key from PULSE_TYPES

    Raises:
        ValueError: If selected type is not in PULSE_TYPES
    """
    choices = ", ".join(PULSE_TYPES)
    selected = input(f"Pulse analysis type ({choices}) [{default}]: ").strip().lower()
    if not selected:
        return default
    if selected not in PULSE_TYPES:
        raise ValueError(
            f"Unknown pulse analysis type '{selected}'. Choose one of: {choices}."
        )
    return selected


pulse_type = select_pulse_type(default="all")
pulse_config = PULSE_TYPES[pulse_type]

#################################
############# LOAD #############
#################################

# set filename suffix and save path based on configuration
suffix = pulse_config["suffix"]
figures_subdir = pulse_config["figures_subdir"]
hist_subdir = pulse_config["hist_subdir"]

# load pulse rate dictionaries from .npz files generated by preprocessing script
data_path = activity_hist_dir(hist_subdir)
pulse_rate_data = np.load(data_path / "berlin_dummypulses_pulse_rate_hz_hist_dict.npz")
pulse_rate_hist_dict = {k: pulse_rate_data[k] for k in pulse_rate_data.files}

# load histogram metadata needed for formatting year-based x-axes
metadata_path = data_path / "berlin_dummypulses_hist_metadata.npz"
if metadata_path.exists():
    metadata = np.load(metadata_path)
    first_month_year = int(metadata["first_month_year"])
    first_month_month = int(metadata["first_month_month"])
    first_year = int(metadata["first_year"])
else:
    # fallback defaults if metadata file is missing
    first_month_year = 2023
    first_month_month = 1
    first_year = 2023

#################################
############# PLOTS #############
#################################

## Output directory for saving generated figures
save_path = processed_figures_dir(figures_subdir)
save_path.mkdir(parents=True, exist_ok=True)


def format_x_axis(axis, timescale, n_bins, data=None):
    """
    Apply timescale-specific tick positions, labels, and consistent x-axis padding.

    Ensures consistent -0.5 to (n_bins - 0.5) limits with custom formatted labels.
    For the 'year' timescale with sparse data, automatically trims trailing empty space.

    Args:
        axis: Matplotlib axis object to format
        timescale (str): Timescale type ('minute', 'hour', 'day', 'month', 'month_since_start', 'year')
        n_bins (int): Number of bins in the histogram
        data: Optional 1D array to check for trailing NaN/zero values (used for sparse data)
    """
    x = np.arange(n_bins)

    # For year timescale with provided data, find last non-NaN value to trim whitespace
    if timescale == "year" and data is not None:
        valid_indices = np.where(~np.isnan(data) & (data != 0))[0]
        if len(valid_indices) > 0:
            last_valid = valid_indices[-1]
            # Adjust n_bins to include last valid bin
            n_bins = last_valid + 1
            x = np.arange(n_bins)

    if timescale == "minute":
        tick_positions = np.arange(0, n_bins, 60)
        tick_labels = [f"{h:02d}:00" for h in range(len(tick_positions))]
        xlabel = "time of day"
    elif timescale == "hour":
        tick_positions = x
        tick_labels = [f"{h:02d}:00" for h in x]
        xlabel = "time of day"
    elif timescale == "month":
        tick_positions = x
        tick_labels = [datetime(2000, m, 1).strftime("%b") for m in range(1, 13)]
        xlabel = "month"
    elif timescale == "month_since_start":
        tick_step = max(1, n_bins // 18)
        tick_positions = x[::tick_step]
        all_labels = month_since_start_labels(n_bins)
        tick_labels = [all_labels[i] for i in tick_positions]
        xlabel = "month since recording start"
    elif timescale == "year":
        tick_positions = x
        tick_labels = [str(y) for y in range(first_year, first_year + n_bins)]
        xlabel = "year"
    else:
        tick_positions = x
        tick_labels = [str(i) for i in x]
        xlabel = "bin index"

    axis.set_xticks(tick_positions)
    axis.set_xticklabels(tick_labels, rotation=45, ha="right")
    axis.set_xlabel(xlabel)
    axis.set_xlim(-0.5, n_bins - 0.5)


def start_y_axis_at_zero(axes):
    """
    Ensure all rate axes are anchored at 0 Hz minimum.

    Args:
        axes: Single or array of Matplotlib axis objects
    """
    for axis in np.ravel(axes):
        axis.set_ylim(bottom=0)


def month_since_start_labels(n_months):
    """
    Generate human-readable labels for absolute month bins.

    Args:
        n_months (int): Number of month bins

    Returns:
        list: Labels in format "MMM YYYY" starting from the metadata's first month
    """
    first_month = datetime(first_month_year, first_month_month, 1)
    return [
        (first_month + relativedelta(months=i)).strftime("%b %Y")
        for i in range(n_months)
    ]


def plot_pulse_rate(
    timescale,
    title,
    filename,
):
    """
    Plot the global recording-effort-normalized pulse rate for one timescale.

    Shows overall activity across all recording sessions as a single line plot.
    X-axis formatting and limits are customized per timescale.
    For year plots, trailing empty space is trimmed based on data.

    Args:
        timescale (str): Timescale type ('minute', 'hour', 'day', 'month', 'month_since_start', 'year')
        title (str): Plot title
        filename (str): Output filename for the saved figure
    """
    if timescale not in pulse_rate_hist_dict:
        return

    rate = pulse_rate_hist_dict[timescale]
    x = np.arange(len(rate))
    fig, ax = plt.subplots(figsize=(20, 6))

    ax.plot(x, rate, color="green")
    # For year plots, pass data to allow trimming trailing whitespace
    format_x_axis(ax, timescale, len(rate), data=rate if timescale == "year" else None)
    ax.set_ylabel("Pulse Rate (Hz)")
    start_y_axis_at_zero(ax)
    fig.suptitle(title)

    plt.tight_layout()
    plt.savefig(save_path / filename, dpi=300)
    plt.show()


def nan_summary(arr):
    """
    Calculate median and percentile statistics ignoring NaN-only bins.

    For bins with no valid data, returns NaN. For bins with some data,
    computes statistics across non-NaN values only.

    Args:
        arr: 2D array with shape (n_sessions, n_bins)

    Returns:
        tuple: (median, p_lo, p_hi) arrays of shape (n_bins,)
               - median: Median value per bin
               - p_lo: 16th percentile per bin
               - p_hi: 84th percentile per bin
    """
    median = np.full(arr.shape[1], np.nan)
    p_lo = np.full(arr.shape[1], np.nan)
    p_hi = np.full(arr.shape[1], np.nan)

    for j in range(arr.shape[1]):
        values = arr[:, j]
        values = values[~np.isnan(values)]
        if values.size == 0:
            continue
        median[j] = np.median(values)
        p_lo[j] = np.percentile(values, 16)
        p_hi[j] = np.percentile(values, 84)

    return median, p_lo, p_hi


def bootstrap_ci_summary(arr, n_bootstrap=10000, ci_level=95):
    """
    Calculate bootstrap confidence intervals around the median for each bin.

    Uses resampling with replacement to estimate the uncertainty in the median
    itself, rather than the spread of individual values. This is more robust
    with sparse data and explicitly quantifies median estimate uncertainty.

    For each bin:
    1. Resample session values with replacement n_bootstrap times
    2. Calculate median for each resample
    3. Use percentiles of bootstrap medians as CI bounds

    Args:
        arr: 2D array with shape (n_sessions, n_bins)
        n_bootstrap (int): Number of bootstrap resampling iterations
        ci_level (int): Confidence level (e.g., 95 for 95% CI)

    Returns:
        tuple: (median, ci_lo, ci_hi) arrays of shape (n_bins,)
               - median: Median value per bin
               - ci_lo: Lower confidence interval bound (e.g., 2.5th percentile for 95% CI)
               - ci_hi: Upper confidence interval bound (e.g., 97.5th percentile for 95% CI)
    """
    median = np.full(arr.shape[1], np.nan)
    ci_lo = np.full(arr.shape[1], np.nan)
    ci_hi = np.full(arr.shape[1], np.nan)

    # Calculate percentile bounds for CI (e.g., 95% CI → 2.5th, 97.5th)
    alpha = (100 - ci_level) / 2
    lower_percentile = alpha
    upper_percentile = 100 - alpha

    for j in tqdm(range(arr.shape[1]), desc="Computing bootstrap CI"):
        values = arr[:, j]
        values = values[~np.isnan(values)]
        if values.size == 0:
            continue

        # Store the true median
        median[j] = np.median(values)

        # Bootstrap: resample and calculate medians
        bootstrap_medians = []
        for _ in range(n_bootstrap):
            # Resample with replacement
            resample = np.random.choice(values, size=len(values), replace=True)
            bootstrap_medians.append(np.median(resample))

        bootstrap_medians = np.array(bootstrap_medians)

        # Get CI bounds from bootstrap distribution
        ci_lo[j] = np.percentile(bootstrap_medians, lower_percentile)
        ci_hi[j] = np.percentile(bootstrap_medians, upper_percentile)

    return median, ci_lo, ci_hi


def plot_session_pulse_rate_summary(timescale, arr):
    """
    Plot per-session pulse rates plus active-session median and percentiles/CI.

    Creates a scatter plot where each point represents one recording session's
    pulse rate in a given time bin. Overlays median and confidence interval (or
    percentile range) computed from active sessions (those with any detected pulses).

    The variation bands can be either:
    - Percentile range (16-84th): Shows spread of individual session values
    - Bootstrap CI: Shows uncertainty in the median estimate itself

    Properly formats x-axis labels and handles padding for all timescales.
    For sparse pulse types, trailing empty bins are excluded from the plot.

    Args:
        timescale (str): Timescale type ('minute', 'hour', 'day', 'month', 'month_since_start', 'year')
        arr: 2D array with shape (n_sessions, n_bins) containing pulse rates
    """
    x = np.arange(arr.shape[1])

    fig, ax = plt.subplots(figsize=(12, 5))

    # Plot scatter points for each session
    for i in range(arr.shape[0]):
        valid = ~np.isnan(arr[i])
        ax.scatter(x[valid], arr[i][valid], alpha=0.2, s=10, color="tab:blue")

    # Summarize active sessions only. Keeping true zero-rate sessions in this
    # summary makes sparse pulse types collapse to a flat 0 Hz median.
    active_arr = np.where(arr > 0, arr, np.nan)

    # Calculate variation estimates using selected method
    if USE_BOOTSTRAP:
        median, ci_lo, ci_hi = bootstrap_ci_summary(
            active_arr, n_bootstrap=BOOTSTRAP_ITERATIONS, ci_level=BOOTSTRAP_CI_LEVEL
        )
        band_label = f"bootstrap {BOOTSTRAP_CI_LEVEL}% CI"
    else:
        median, ci_lo, ci_hi = nan_summary(active_arr)
        band_label = "active-session 16-84th pct"

    median_m = np.ma.masked_invalid(median)
    ci_lo_m = np.ma.masked_invalid(ci_lo)
    ci_hi_m = np.ma.masked_invalid(ci_hi)

    ax.plot(
        x,
        median_m,
        color="tab:red",
        linewidth=1.5,
        label="active-session median",
    )
    ax.fill_between(
        x,
        ci_lo_m,
        ci_hi_m,
        color="tab:red",
        alpha=0.25,
        label=band_label,
    )

    # Format x-axis with proper labels and padding
    # For year plots, pass median data to allow trimming trailing whitespace
    format_x_axis(
        ax, timescale, arr.shape[1], data=median if timescale == "year" else None
    )
    ax.set_ylabel("Pulse Rate (Hz)")
    ax.set_ylim(bottom=0)
    ax.legend(loc="upper right", fontsize="small")
    plt.title(timescale)
    plt.tight_layout()
    plt.savefig(save_path / f"{timescale}{suffix}.png", dpi=300)
    plt.show()


# %%
## GLOBAL PULSE RATE PLOTS - Overall activity across all recording sessions

## 24 hours - minute bins (1440 bins per 24-h cycle)
plot_pulse_rate(
    "minute",
    "24-hour pulse rate histogram (1-min bins)",
    f"24h_minute{suffix}.png",
)


# %%
## 24 hours - hourly bins (24 bins per 24-h cycle)
plot_pulse_rate(
    "hour",
    "24-hour pulse rate histogram (hourly bins)",
    f"24h_hour{suffix}.png",
)


# %%
## Months - monthly bins within a year (12 bins)
plot_pulse_rate(
    "month",
    "monthly pulse rate histogram (monthly bins)",
    f"12month_month{suffix}.png",
)


# %%
## Months since recording start - monthly bins (spans entire recording period)
plot_pulse_rate(
    "month_since_start",
    "monthly pulse rate histogram since recording start (monthly bins)",
    f"months_since_start_month{suffix}.png",
)


# %%
## Years - yearly bins (spans entire recording period)
plot_pulse_rate(
    "year",
    "yearly pulse rate histogram (yearly bins)",
    f"years_year{suffix}.png",
)


# %%
## SESSION-WISE SCATTER PLOTS - Per-session activity plus aggregate statistics

# Load per-session pulse rate data
data = np.load(data_path / "berlin_dummypulses_session_pulse_rate_hz.npz")
for timescale in data.files:
    # Skip day timescale (too granular for meaningful session-wise visualization)
    if timescale == "day":
        continue

    arr = data[timescale]  # shape (n_sessions, n_bins)
    plot_session_pulse_rate_summary(timescale, arr)


# TODO: clean up script, modularize, make functions
# %%
